INSERT INTO supplier (name, country) VALUES ('Test supplier', 'Spain');
INSERT INTO supplier (name, country) VALUES ('Supplier 2', 'Italy');

INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('admin', 'admin', 1);
INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('user', 'user', 0);
INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('user2', 'user', 0);

INSERT INTO ITEM (ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATOR_USER_ID) VALUES (1, 'Blue table', '45.90', 0, 2 );
INSERT INTO ITEM (ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATOR_USER_ID) VALUES (2, 'Green sofa', '458.90', 0, 3 );
INSERT INTO ITEM (ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATOR_USER_ID) VALUES (6, 'White table', '30', 0, 2 );
INSERT INTO ITEM (ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATOR_USER_ID) VALUES (9, 'Green sofa with stripes', '300.90', 0, 2 );

INSERT INTO ITEM_SUPPLIERS (ITEM_ITEM_ID, SUPPLIERS_SUPPLIER_ID  ) VALUES (1,1);
INSERT INTO ITEM_SUPPLIERS (ITEM_ITEM_ID, SUPPLIERS_SUPPLIER_ID  ) VALUES (1,2);
INSERT INTO ITEM_SUPPLIERS (ITEM_ITEM_ID, SUPPLIERS_SUPPLIER_ID  ) VALUES (3,2);